export const Keys = {
    DEFAULT_WIDTH: 'prefs-default-width',
    DEFAULT_HEIGHT: 'prefs-default-height',
    INDICATOR_POSITION: 'indicator-position',
    INDICATOR_INDEX: 'indicator-position-index',
    INDICATOR_POS_MAX: 'indicator-position-max',
    USERNAME: 'username',
    PASSWORD: 'password',
    API_SOURCE: 'api-source',
    ACCESS_TOKEN: 'access-token',
    LIBRE_LINK_API_URL: 'libre-link-api-url',
    LIBRE_LINK_UP_VERSION: 'libre-link-up-version',
    ACCOUNT_ID: 'account-id',
    REFRESH_INTERVAL: 'refresh-interval',
    LOW_THRESHOLD: 'low-threshold',
    HIGH_THRESHOLD: 'high-threshold',
};
